version: '3.4'

services:
  cooking_service:
    image: cooking_service:9.2
    ports:
      - "70:80"
    depends_on:
      "rabbitmq":
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  bread_service:
    image: bread_service:9.1
    ports:
      - "80:80"
    depends_on:
      "cooking_service":
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  cheese_service:
    image: cheese_service:9.1
    ports:
      - "50:80"
    depends_on:
      "cooking_service":
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  rabbitmq:
    image: rabbitmq:3.0
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
        - my-network
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "15672"]
      interval: 30s
      timeout: 30s
      retries: 2
      start_period: 30s

networks:
  my-network:
    external: true





