version: '3.4'

services:
  cooking_service:
    image: helenixx/cooking_service:main
    ports:
      - "2000:80"
    depends_on:
      "rabbitmq":
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  steak_service:
    image: helenixx/steak_service:main
    ports:
      - "3000:80"
    depends_on:
      "cooking_service":
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  bacon_service:
    image: helenixx/bacon_service:main
    ports:
      - "3200:80"
    depends_on:
      "cooking_service":
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  tomato_service:
    image: helenixx/tomato_service:main
    ports:
      - "3400:80"
    depends_on:
      "cooking_service":
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  lettuce_service:
    image: helenixx/lettuce_service:main
    ports:
      - "3600:80"
    depends_on:
      "cooking_service":
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  pickle_service:
    image: helenixx/pickle_service:main
    ports:
      - "3800:80"
    depends_on:
      "cooking_service":
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  cheese_service:
    image: helenixx/cheese_service:main
    ports:
      - "4000:80"
    depends_on:
      "cooking_service":
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  hamburguer_client:
    image: helenixx/app_service:main
    ports:
      - "49160:8080"
    depends_on:
      "cheese_service":
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PORT=8080
    networks:
        - my-network

  rabbitmq:
    image: helenixx/rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
        - my-network
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "15672"]
      interval: 30s
      timeout: 30s
      retries: 2
      start_period: 30s

networks:
  my-network:
    external: true





