version: '3.4'

services:
  cooking_service:
    image: cooking_service:10.0
    ports:
      - "2000:80"
    depends_on:
      "rabbitmq":
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  cheese_service:
    image: cheese_service:10.0
    ports:
      - "4000:80"
    depends_on:
      "cooking_service":
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
        - my-network

  hamburguer_client:
    image: hamburger-client:latest
    ports:
      - "49160:8080"
    depends_on:
      "cheese_service":
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PORT=8080
    networks:
        - my-network

  rabbitmq:
    image: rabbitmq:3.0
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
        - my-network
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "15672"]
      interval: 30s
      timeout: 30s
      retries: 2
      start_period: 30s

networks:
  my-network:
    external: true





