name: Pickle CI

on:
  pull_request:
    types:
      - opened
    branches:
      - 'master/pickle-service'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build PickleService --file PickleService/Dockerfile --tag pickle_service:$(date +%s)
